### PR TITLE
Use preset-env to support older browsers

### PR DESCRIPTION
**Pull request by jariz**
Don't merge yet!

I've implemented everything we talked about in #9, however, it's now throwing strange errors when building my project:
```
error Plugin gatsby-plugin-graphql-preview returned an error
  ReferenceError: isolatedQueries is not defined

  - gatsby-node.js:136 _callee$
    /Users/Jari/Copy/www/gatsby-plugin-graphql-preview/gatsby-node.js:136:29

```

Maybe you can take a look? I don't really get what's going here.

### CODE REVIEW

**Comment by djfarly** [comment]
I think I missed a `const` in `src/lib/node/onCreateWebpackConfig.js:11`.

**Comment by jariz** [comment]
@djfarly Correct. That fixed it.

I also downgraded `query-string` to v5 because v6 shipped ES6 code.
Still seems to be working fine.

**Comment by djfarly** [comment]
Looks very good! Tyvm. 🙌

**Pull request merged**
